name: sipresensi_mobile
description: "Aplikasi presensi digital sekolah."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  camera: ^0.11.0+1
  mobile_scanner: ^5.1.1
  file_picker: ^8.0.3
  table_calendar: ^3.1.2
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  flutter_quill: 11.4.2
  flutter_offline: ^3.0.1
  hive: ^2.2.3
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true